import { Lesson, SentenceScramble, VocabularyItem } from "@/lib/types";

export const demoLessons: Lesson[] = [
  {
    id: "demo-lesson-1",
    level: 1,
    unit: 1,
    lesson_number: 1,
    sequence_number: 1,
    sort_order: 1,
    title_en: "Daily Life",
    title_es: "Vida Diaria",
    title_pt: "Vida Diária",
    description_en: "Essential EnglishConnect starter words.",
    description_es: "Palabras iniciales esenciales de EnglishConnect.",
    description_pt: "Palavras iniciais essenciais do EnglishConnect.",
  },
];

export const demoVocabulary: VocabularyItem[] = [
  {
    id: "v1",
    lesson_id: "demo-lesson-1",
    source_row_id: 1,
    item_type: "word",
    english_text: "family",
    english_sentence: "I love my family",
    spanish_text: "familia",
    portuguese_text: "família",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
  {
    id: "v2",
    lesson_id: "demo-lesson-1",
    source_row_id: 2,
    item_type: "word",
    english_text: "work",
    english_sentence: "I work every day",
    spanish_text: "trabajo",
    portuguese_text: "trabalho",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
  {
    id: "v3",
    lesson_id: "demo-lesson-1",
    source_row_id: 3,
    item_type: "word",
    english_text: "church",
    english_sentence: "We go to church on Sunday",
    spanish_text: "iglesia",
    portuguese_text: "igreja",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
  {
    id: "v4",
    lesson_id: "demo-lesson-1",
    source_row_id: 4,
    item_type: "word",
    english_text: "study",
    english_sentence: "I study English",
    spanish_text: "estudiar",
    portuguese_text: "estudar",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
  {
    id: "v5",
    lesson_id: "demo-lesson-1",
    source_row_id: 5,
    item_type: "word",
    english_text: "friend",
    english_sentence: "My friend is kind",
    spanish_text: "amigo",
    portuguese_text: "amigo",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
  {
    id: "v6",
    lesson_id: "demo-lesson-1",
    source_row_id: 6,
    item_type: "word",
    english_text: "food",
    english_sentence: "This food is good",
    spanish_text: "comida",
    portuguese_text: "comida",
    spanish_transliteration: null,
    portuguese_transliteration: null,
    ipa: null,
    part_of_speech: null,
    definition: null,
    image_url: null,
    audio_url: null,
    difficulty_level: 1,
  },
];

export const demoScrambles: SentenceScramble[] = [
  {
    id: "s1",
    lesson_id: "demo-lesson-1",
    english_sentence: "I am learning English today",
    spanish_hint: "Estoy aprendiendo inglés hoy",
    portuguese_hint: "Estou aprendendo inglês hoje",
  },
  {
    id: "s2",
    lesson_id: "demo-lesson-1",
    english_sentence: "My family studies together",
    spanish_hint: "Mi familia estudia junta",
    portuguese_hint: "Minha família estuda junto",
  },
];
